### ISSUE TITLE
Onboard Sensor Gyrpskop

### ISSUE THREAD

**Issue by FlederJ** [zockerhuhn/Arduino-4.0-2024_2025#39]
Bei Rampen wird das Kreuzungsprogramm ausgeführt, weil die Reflektionssensoren angehoben werden. Um dies zu verhindern, muss mit einem Gyroskop die Schräge festgestellt werden, damit das Kreuzungsprogramm nicht fälschlich ausgeführt wird.

**Comment by zockerhuhn** [comment]
Use #30
